name: knn-demo-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8.3      
  - numpy=1.22.4      
  - matplotlib=3.2.2
  - scikit-learn=1.3.2 
  - ipywidgets=7.5.1
  - ipython=7.16.1
  - notebook=6.0.3
  - pip               
